/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coctailappforms;
import cocktailapp.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class AddIngrediant extends javax.swing.JFrame {
    static Blender blender;
    

    /**
     * Creates new form AddIngrediant
     */
    public AddIngrediant(Blender blender) {
        this.blender = blender;
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Login2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        volFruit = new javax.swing.JTextField();
        calFruit = new javax.swing.JTextField();
        labcalorise4 = new javax.swing.JLabel();
        labvolum4 = new javax.swing.JLabel();
        strawbary = new javax.swing.JButton();
        mango = new javax.swing.JButton();
        orange = new javax.swing.JButton();
        banana = new javax.swing.JButton();
        bluebarry = new javax.swing.JButton();
        kiwi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        calMilk = new javax.swing.JTextField();
        labcalorise3 = new javax.swing.JLabel();
        labvolum3 = new javax.swing.JLabel();
        volMilk = new javax.swing.JTextField();
        whiteMilk = new javax.swing.JButton();
        blushMilk = new javax.swing.JButton();
        yellowMilk = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        calSuger = new javax.swing.JTextField();
        labcalorise2 = new javax.swing.JLabel();
        whiteSuger = new javax.swing.JButton();
        brownSuger = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add ingredients");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 249, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cocktail.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        Login2.setBackground(new java.awt.Color(255, 249, 255));
        Login2.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        Login2.setForeground(new java.awt.Color(153, 153, 0));
        Login2.setText("Finish");
        Login2.setAlignmentY(0.0F);
        Login2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login2ActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 249, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBackground(new java.awt.Color(255, 249, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.21.54 AM.jpeg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.21.58 AM.jpeg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.21.50 AM.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.21.04 AM.jpeg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.21.11 AM.jpeg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.36.06 AM.jpeg"))); // NOI18N

        volFruit.setEditable(false);
        volFruit.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N

        calFruit.setEditable(false);
        calFruit.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N

        labcalorise4.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        labcalorise4.setForeground(new java.awt.Color(153, 153, 0));
        labcalorise4.setText("Calories :");

        labvolum4.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        labvolum4.setForeground(new java.awt.Color(153, 153, 0));
        labvolum4.setText("Volum (ml) :");

        strawbary.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        strawbary.setForeground(new java.awt.Color(153, 153, 0));
        strawbary.setText("Strawberry");
        strawbary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawbaryActionPerformed(evt);
            }
        });

        mango.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        mango.setForeground(new java.awt.Color(153, 153, 0));
        mango.setText("Mango");
        mango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangoActionPerformed(evt);
            }
        });

        orange.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        orange.setForeground(new java.awt.Color(153, 153, 0));
        orange.setText("Orange");
        orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeActionPerformed(evt);
            }
        });

        banana.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        banana.setForeground(new java.awt.Color(153, 153, 0));
        banana.setText("Banana");
        banana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bananaActionPerformed(evt);
            }
        });

        bluebarry.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        bluebarry.setForeground(new java.awt.Color(153, 153, 0));
        bluebarry.setText("Blueberry");
        bluebarry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bluebarryActionPerformed(evt);
            }
        });

        kiwi.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        kiwi.setForeground(new java.awt.Color(153, 153, 0));
        kiwi.setText("Kiwi");
        kiwi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiwiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labvolum4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strawbary)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(banana))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mango))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(kiwi)
                                .addGap(4, 4, 4)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(bluebarry))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orange)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labcalorise4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(volFruit)
                            .addComponent(calFruit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(strawbary))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mango)
                            .addComponent(orange))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bluebarry)
                        .addComponent(kiwi))
                    .addComponent(banana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(labcalorise4)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calFruit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labvolum4)
                    .addComponent(volFruit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fruits", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 249, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.32.13 AM (1).jpeg"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/yellowMilk.jpeg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.21.24 AM.jpeg"))); // NOI18N

        calMilk.setEditable(false);
        calMilk.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N

        labcalorise3.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        labcalorise3.setForeground(new java.awt.Color(153, 153, 0));
        labcalorise3.setText("Calories :");

        labvolum3.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        labvolum3.setForeground(new java.awt.Color(153, 153, 0));
        labvolum3.setText("Volum (ml) :");

        volMilk.setEditable(false);
        volMilk.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N

        whiteMilk.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        whiteMilk.setForeground(new java.awt.Color(153, 153, 0));
        whiteMilk.setText("White Milk");
        whiteMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteMilkActionPerformed(evt);
            }
        });

        blushMilk.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        blushMilk.setForeground(new java.awt.Color(153, 153, 0));
        blushMilk.setText("Bluish Milk");
        blushMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blushMilkActionPerformed(evt);
            }
        });

        yellowMilk.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        yellowMilk.setForeground(new java.awt.Color(153, 153, 0));
        yellowMilk.setText("Yellow Milk");
        yellowMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowMilkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labcalorise3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(volMilk)
                            .addComponent(calMilk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labvolum3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(whiteMilk)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(yellowMilk)
                        .addGap(27, 27, 27)
                        .addComponent(blushMilk))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel12)))
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blushMilk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yellowMilk)
                                .addComponent(whiteMilk)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(labcalorise3)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(calMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labvolum3)
                    .addComponent(volMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );

        jTabbedPane1.addTab("Milk", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 249, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.21.19 AM.jpeg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/WhatsApp Image 2024-05-20 at 2.22.17 AM.jpeg"))); // NOI18N
        jLabel9.setToolTipText("");

        calSuger.setEditable(false);
        calSuger.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N

        labcalorise2.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        labcalorise2.setForeground(new java.awt.Color(153, 153, 0));
        labcalorise2.setText("Calories :");
        labcalorise2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        whiteSuger.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        whiteSuger.setForeground(new java.awt.Color(153, 153, 0));
        whiteSuger.setText("White Suger");
        whiteSuger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteSugerActionPerformed(evt);
            }
        });

        brownSuger.setFont(new java.awt.Font("Z003", 0, 18)); // NOI18N
        brownSuger.setForeground(new java.awt.Color(153, 153, 0));
        brownSuger.setText("Brown Suger");
        brownSuger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownSugerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(whiteSuger)
                        .addGap(82, 82, 82)
                        .addComponent(brownSuger))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labcalorise2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calSuger, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whiteSuger)
                    .addComponent(brownSuger))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calSuger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labcalorise2))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Suger", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Login2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Login2)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double caloriseF = 0.0;
    double caloriseM = 0.0;
    double caloriseS = 0.0;
    double volumeF = 0.0;
    double volumeM = 0.0;
    
    public void update(Ingredient i){
        try {
        caloriseF += i.getNumberOfCalories();  //new
        volumeF += i.getVolume();              // new

            if(blender.getVolume() < blender.getCapacity()){
                blender.add(i);            
                calFruit.setText(caloriseF+"");
                calMilk.setText(caloriseM+"");
                calSuger.setText(caloriseS+"");
                volFruit.setText(volumeF+"");
                volMilk.setText(volumeM+"");
            }
            else{
                JOptionPane.showMessageDialog(null, "Blender is Full");
            }
        } catch (OverFlowExeption ex) {
            Logger.getLogger(AddIngrediant.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void Login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login2ActionPerformed
        this.setVisible(false);
        new MakerPage(blender).setVisible(true);

    }//GEN-LAST:event_Login2ActionPerformed

    private void strawbaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawbaryActionPerformed
        Fruit i = new Fruit("Strawberry", 4, 100);
        update(i);
        caloriseF += i.getNumberOfCalories();
        volumeF += i.getVolume();
    }//GEN-LAST:event_strawbaryActionPerformed

    private void mangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangoActionPerformed
        Fruit i = new Fruit("Mango", 56, 100);
        update(i);
        caloriseF += i.getNumberOfCalories();
        volumeF += i.getVolume();
    }//GEN-LAST:event_mangoActionPerformed

    private void orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeActionPerformed
        Fruit i = new Fruit("Orange", 57, 100);
        update(i);
        caloriseF += i.getNumberOfCalories();
        volumeF += i.getVolume();
    }//GEN-LAST:event_orangeActionPerformed

    private void bananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bananaActionPerformed
        Fruit i = new Fruit("Banana", 90, 100);
        update(i);
        caloriseF += i.getNumberOfCalories();
        volumeF += i.getVolume();
    }//GEN-LAST:event_bananaActionPerformed

    private void bluebarryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bluebarryActionPerformed
        Fruit i = new Fruit("Blueberry", 55, 100);
        update(i);
        caloriseF += i.getNumberOfCalories();
        volumeF += i.getVolume();
    }//GEN-LAST:event_bluebarryActionPerformed

    private void kiwiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiwiActionPerformed
        Fruit i = new Fruit("Kiwi", 42, 100);
        update(i);
        caloriseF += i.getNumberOfCalories();
        volumeF += i.getVolume();
    }//GEN-LAST:event_kiwiActionPerformed

    private void whiteMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteMilkActionPerformed
       Milk i = new Milk("White Milk", 50, 100);
       update(i);
       caloriseM += i.getNumberOfCalories();
       volumeM += i.getVolume();
       
        calMilk.setText(caloriseM+"");  //new
        volMilk.setText(volumeM+"");    //new
    }//GEN-LAST:event_whiteMilkActionPerformed

    private void blushMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blushMilkActionPerformed
        Milk i = new Milk("Bluish Milk", 50, 100);
        update(i);
        caloriseM += i.getNumberOfCalories();
        volumeM += i.getVolume();
        
        calMilk.setText(caloriseM+"");   //new
        volMilk.setText(volumeM+"");     //new
    }//GEN-LAST:event_blushMilkActionPerformed

    private void whiteSugerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteSugerActionPerformed
       Suger i = new Suger("White Sugar", 800);
       update(i);
       caloriseS += i.getNumberOfCalories();
       
      calSuger.setText(caloriseS+"");  //new
    }//GEN-LAST:event_whiteSugerActionPerformed

    private void brownSugerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brownSugerActionPerformed
       Suger i = new Suger("Brown Sugar", 680);
       update(i);
       caloriseS += i.getNumberOfCalories();
       
        calSuger.setText(caloriseS+"");   //new
    }//GEN-LAST:event_brownSugerActionPerformed

    private void yellowMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowMilkActionPerformed
        Milk i = new Milk("Yellow Milk", 50, 100);
        update(i);
        caloriseM += i.getNumberOfCalories();  //new
        volumeM += i.getVolume();              //new
        
        calMilk.setText(caloriseM+"");
        volMilk.setText(volumeM+"");
    }//GEN-LAST:event_yellowMilkActionPerformed



    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddIngrediant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddIngrediant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddIngrediant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddIngrediant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddIngrediant(blender).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login2;
    private javax.swing.JButton banana;
    private javax.swing.JButton bluebarry;
    private javax.swing.JButton blushMilk;
    private javax.swing.JButton brownSuger;
    private javax.swing.JTextField calFruit;
    private javax.swing.JTextField calMilk;
    private javax.swing.JTextField calSuger;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kiwi;
    private javax.swing.JLabel labcalorise2;
    private javax.swing.JLabel labcalorise3;
    private javax.swing.JLabel labcalorise4;
    private javax.swing.JLabel labvolum3;
    private javax.swing.JLabel labvolum4;
    private javax.swing.JButton mango;
    private javax.swing.JButton orange;
    private javax.swing.JButton strawbary;
    private javax.swing.JTextField volFruit;
    private javax.swing.JTextField volMilk;
    private javax.swing.JButton whiteMilk;
    private javax.swing.JButton whiteSuger;
    private javax.swing.JButton yellowMilk;
    // End of variables declaration//GEN-END:variables
}
