/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coctailappforms;
import cocktailapp.*;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author maram
 */
public class CocktailLogin extends javax.swing.JFrame {
        InterfaceLogger logger = new MyLogger() ;
        
    /**
     * Creates new form CocktailLogin
     */
    public CocktailLogin() {
        
        initComponents();
        this.setLocationRelativeTo(null); //new
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        console = new javax.swing.JButton();
        File = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login window");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 249, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cocktail3.png"))); // NOI18N

        Text.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        Text.setForeground(new java.awt.Color(153, 153, 0));
        Text.setText("Let's make the most delicious cocktail");

        Login.setBackground(new java.awt.Color(255, 249, 255));
        Login.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        Login.setForeground(new java.awt.Color(153, 153, 0));
        Login.setText("Login");
        Login.setAlignmentY(0.0F);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        console.setBackground(new java.awt.Color(255, 249, 255));
        console.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        console.setForeground(new java.awt.Color(153, 153, 0));
        console.setText("Console");
        console.setAlignmentY(0.0F);
        console.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        console.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleActionPerformed(evt);
            }
        });

        File.setBackground(new java.awt.Color(255, 249, 255));
        File.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        File.setForeground(new java.awt.Color(153, 153, 0));
        File.setText("File");
        File.setAlignmentY(0.0F);
        File.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(console, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(File, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Text)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Text)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(console)
                    .addComponent(File))
                .addGap(44, 44, 44)
                .addComponent(Login)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        this.setVisible(false);
        Blender blender = new Blender(1000, logger);
        new MakerPage(blender).setVisible(true);
    }//GEN-LAST:event_LoginActionPerformed

    private void consoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleActionPerformed
        
        logger = new MyLogger();
    }//GEN-LAST:event_consoleActionPerformed

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        File file = null;
        JFileChooser chooser =new JFileChooser();
        int retVal = chooser.showOpenDialog(this);
        
        if(retVal == JFileChooser.APPROVE_OPTION){
        file=chooser.getSelectedFile();
        }
        String filePath=  file.getPath();
        logger = new FileLogger(filePath);
        
    }//GEN-LAST:event_FileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CocktailLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CocktailLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CocktailLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CocktailLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CocktailLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton File;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Text;
    private javax.swing.JButton console;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
